### ISSUE TITLE
npwd broken

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_npwd#5]
### Summary

npwd broken
ref images

### Additional context

![image](https://github.com/Qbox-project/qbx_npwd/assets/92496158/1704b176-6a78-4e1c-999e-26f5f7aed1b4)
![image](https://github.com/Qbox-project/qbx_npwd/assets/92496158/2398cfa0-00ea-4df6-b961-bb45834fa2c6)

### Last Updated

today

**Comment by dusan01** [comment]
What version of NPWD are you using? Are these the latest versions?

**Comment by TonybynMp4** [comment]
It's a "user error" (also called a you problem),
you must've installed npwd incorrectly / have the wrong order in your server.cfg.

make sure you download npwd.zip from the latest [release](https://github.com/project-error/npwd/releases/latest),
the *correct* order to start the resources is:
ensure qbx_npwd
ensure npwd
